package configuration.pronos;

public enum PronosContext {
    PRONO_TITLE, NEW_COTE, PRONO_ATTEMPT, PUBLISH_ERROR,
    SUBSCRIBE_ATTEMPT /* la tentative d'abonnement */, SUBSCRIBE_ERROR, SUBSCRIBE_PRIZE, RETRIEVE_ERROR, NEW_PRONO, NOT_DISAPPROVALABLE, ALREADY_DISAPPROVED, NOT_DECIDABLE
}
